# uninstall golang https://howtoinstall.co/en/golang-go?action=remove
- name: Uninstall go-golang
  ansible.builtin.apt:
    name: go-golang
    state: absent
    purge: true
    force_apt_get: true
- name: Autoremove packages
  ansible.builtin.apt:
    autoremove: yes
    force_apt_get: true
- name: Download Golang
  ansible.builtin.get_url:
    url: "https://go.dev/dl/go{{ golang_version }}.linux-amd64.tar.gz"
    dest: "/tmp/{{ golang_version }}.linux-amd64.tar.gz"
    checksum: "sha256:{{ golang_package_sha256 }}"
- name: Extract golang archive into {{ golang_path }} folder
  ansible.builtin.unarchive:
    src: "/tmp/{{ golang_version }}.linux-amd64.tar.gz"
    dest: "{{ golang_path }}"
    remote_src: yes
