---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: "Include curuvija.ansible_role_golang"
      ansible.builtin.include_role:
        name: "curuvija.ansible_role_golang"
