---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
  flake8 .
platforms:
  - name: ubuntu2004-molecule
    image: curuvija/molecule_ubuntu2004:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
