- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: "Stat /usr/local/go exists"
      ansible.builtin.stat:
        path: /usr/local/go
      register: golang_path_stat
    - name: "Check if /usr/local/go exists"
      ansible.builtin.assert:
        that:
          - golang_path_stat.stat.exists == True
        success_msg: "/usr/local/go exists"
        fail_msg: "/usr/local/go does not exist"
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: apt
    - name: "Check go-golang is absent"
      ansible.builtin.assert:
        that:
          - "'golang-go' not in ansible_facts.packages"
        success_msg: "go-golang not present"
        fail_msg: "go-golang is still present"
    - name: "Get go version"
      ansible.builtin.command: "/usr/local/go/bin/go version"
      register: golang_version
      changed_when: false
    - name: "Check installed golang version"
      ansible.builtin.assert:
        that:
          - "'go1.21.0' in golang_version.stdout"
        success_msg: "installed golang version is correct"
        fail_msg: "installed golang version is not correct"
